### PR TITLE
Update `wat` to version 1.216.0

### PR DESCRIPTION
**Pull request by jvff**
# Motivation

Wasmtime requires a newer version of `wat` than the one pinned by `wasmer`.

# Solution

Update `wat` to the latest version, and update the MSRV to support the newer version of `wat`.

### CODE REVIEW

**Comment by Twey** [comment]
I think this is sufficient!  The upstream branch has a pinned version of `wast` they use as well, but I think only for testing from what I can see.

**Review by Twey — APPROVED** [review]

**Comment by Twey** [comment]
Oh, but this seems to be based off an older version.  The crates we've released are `linera.2` — this change should bump it to `linera.3`.

**Comment by jvff** [comment]
I figured we should reset the `linera.#` suffix if the upstream version is different. In this case it went from `4.3.1-linera.2` to `4.3.6-linera.1`. Does this make sense?

**Comment by Twey** [comment]
An interesting question!  I think that the `linera.X` version number tracks the version of the Linera patchset, so it's orthogonal to the `wasmer` version.  When we move from (e.g.) `4.3.3` to `4.4.0`, we reset the last component because all of the changes denoted by the patch component are now included in the minor component.  But in our case Wasmer 4.3.6 does not include the changes denoted by `linera.2` in `4.3.1-linera.2`, so I don't think the number should reset.

**Comment by jvff** [comment]
Got it. I think I fixed it. Let me know if it's okay.

**Comment by Twey** [comment]
Looks good to me!

(posterity: `linera.2` was bumped to `linera.3` as part of the rebase already)

**Review by Twey — APPROVED** [review]

**Pull request merged**
